---
- name: Upgrade Kubernetes nodes (kured handles reboots)
  hosts: kubernetes
  become: true
  gather_facts: false
  serial: 1
  
  tasks:
    - name: Update archlinux-keyring first
      become_user: ansible
      shell: paru -S --noconfirm archlinux-keyring
      changed_when: false
      failed_when: false

    - name: Check for available upgrades
      become_user: ansible
      shell: paru -Sy --noconfirm && paru -Qu
      register: paru_upgrades
      changed_when: false
      failed_when: false

    - name: Show packages to be upgraded
      debug:
        msg: "{{ paru_upgrades.stdout_lines }}"
      when: paru_upgrades.stdout != ""

    - name: Upgrade all packages
      become_user: ansible
      shell: paru -Syu --noconfirm
      environment:
        LANG: C
        LC_ALL: C
      when: paru_upgrades.stdout != ""
